### PR TITLE
RHIDP-1703: Revert querying of OCP Cluster Ingress

### PR DESCRIPTION
**Pull request by coreydaley**
Revert the automatic querying of the OCP Cluster Ingress for the domain to use for the clusterRouterBase as regular users do not have access to this resource, only cluster admins.

## Checklist

- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [x] Variables are documented in the `values.yaml` and added to the README.md. The [pre-commit](https://pre-commit.com/) utility can be used to generate the necessary content. Use `pre-commit run -a` to apply changes.
- [ ] JSON Schema template updated and re-generated the raw schema via `pre-commit` hook.
- [ ] List tests pass for Chart using the [Chart Testing](https://github.com/helm/chart-testing) tool and the `ct lint` command.

### CODE REVIEW

**Review by rm3l — COMMENTED** [review]
> Revert the automatic querying of the OCP Cluster Ingress for the domain to use for the clusterRouterBase as regular users do not have access to this resource, only cluster admins.

I guess the issue that the reverted commit was supposed to fix should be somehow reopened here or in JIRA as not fixed?
https://github.com/janus-idp/helm-backstage/issues/167?

**Comment by nickboldt** [comment]
> > Revert the automatic querying of the OCP Cluster Ingress for the domain to use for the clusterRouterBase as regular users do not have access to this resource, only cluster admins.
> 
> I guess the issue that the reverted commit was supposed to fix should be somehow reopened here or in JIRA as not fixed? [janus-idp#167](https://github.com/janus-idp/helm-backstage/issues/167)?

makes sense, yeah

**Comment by coreydaley** [comment]
@rm3l From what I can see there is not a programmatical way to solve this issue. The issue is really solved via the documentation that describes what information should be placed in the clusterRouterBase field. I was also thinking that maybe we could just have this code run if the user is a cluster-admin, but I don't see a way using helm to determine that as the install just fails on the lookup command, even if it is just used in an if block.

**Review by nickboldt — APPROVED** [review]

**Review by PatAKnight — APPROVED** [review]

**Comment by coreydaley** [comment]
Two approvals, I am going to go ahead and merge this.

**Comment by rm3l** [comment]
> @rm3l From what I can see there is not a programmatical way to solve this issue due to limitations in Helm. The issue is really solved via the documentation that describes what information should be placed in the clusterRouterBase field. I was also thinking that maybe we could just have this code run if the user is a cluster-admin, but I don't see a way using helm to determine that as the install just fails on the lookup command, even if it is just used in an if block.

No problem, just wanted to make sure that people who reported the original issue (https://github.com/janus-idp/helm-backstage/issues/167) were aware of this revert in case they expected the original issue to have been implemented (and were maybe depending on it) in which case this PR would have been a potential breaking change.
But after a closer look at https://github.com/janus-idp/helm-backstage/issues/167, it was requested in https://github.com/parodos-dev/orchestrator-helm-chart/issues/12. But it seems from [their Chart.yaml](https://github.com/parodos-dev/orchestrator-helm-chart/blob/main/charts/orchestrator/Chart.yaml) that they are no longer using the RHDH Chart, but are now using the RHDH Operator instead.
So I guess we don't need to create a JIRA issue for https://github.com/janus-idp/helm-backstage/issues/167

**Pull request merged**
